public class ContactCountHandler {
    //Question 1 :)
    public static void afterInsertHandler(List<Contact> listOfContact) {
        ContactCountHelper.afterInsertHelper(listOfContact);
    }
    public static void afterDeleteHandler(List<Contact> listOfContact) {
        ContactCountHelper.afterInsertHelper(listOfContact);
    }
    
    
    
   
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /*//Question 10 :)
    public static void afterUpdateHandler(List<Contact> listofContact){
        ContactCountHelper.afterUpdateHelper(listofContact);        
    }*/
}