public class LeadRecordPostApiCallHandler {
    //Question 2 :)
    public static void afterInsertHandler(List<Lead> listOfNewLead){
        LeadRecordPostApiCallHelper.afterInsertHelper(listOfNewLead);
    }
    
   
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /*//Question 7 :)
    public static void afterUpdateHandler(List<Lead> listOfUpdateLead){
        LeadRecordPostApiCallHelper.afterUpdateHelper(listOfUpdateLead);
    }*/

}